export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_LOGOUT = "LOGIN_LOGOUT";

export const WORKOUT_PLANS_REQUEST = "WORKOUT_PLANS_REQUEST";
export const WORKOUT_PLANS_SUCCESS = "WORKOUT_PLANS_SUCCESS";
export const WORKOUT_PLANS_FAIL = "WORKOUT_PLANS_FAIL";
export const ADD_WORKOUT_PLAN = "ADD_WORKOUT_PLAN";
export const REMOVE_WORKOUT_PLAN = "REMOVE_WORKOUT_PLAN";

export const ENABLE_HAMBURGER_MENU = "ENABLE_HAMBURGER_MENU";
export const DISABLE_HAMBURGER_MENU = "DISABLE_HAMBURGER_MENU";
